### PR TITLE
chore(deps): RuboCop v0.80.x

### PR DESCRIPTION
**Pull request by DirtyF**
- [x] The `master` branch of the Jekyll Repository has been updated to use the latest RuboCop release.
  - [x] updated ONLY the badge in the `README.md`.
  - [x] updated ONLY the RuboCop version in the `rubocop-jekyll.gemspec`.
  - [x] updated the `.rubocop.yml`

Rubocop Changelog: https://github.com/rubocop-hq/rubocop/releases

Tested on a few plugins and very minor changes so far.

### CODE REVIEW

**Comment by ashmaroli** [comment]
Thank you for submitting this upgrade, @DirtyF 
I was hesitant to make the change myself because the change in the cop names could break downstream projects overriding the old cops.

That's sad because this gem was also created to reduce the maintenance overhead from having to track the change in RuboCop cop names..

In other words, I was waiting for RuboCop to stabilize with its v1.0 ...

**Comment by DirtyF** [comment]
As you can see, for now, there are no breaking changes, just some warnings. I'm OK with not upgrading for _every_ minor Rubocop version, maybe only release a new version of this plugin every 6 months.

**Comment by DirtyF** [comment]
💚 💚 💚

**Comment by ashmaroli** [comment]
The Travis tests needs fixing.. The jobs use the `master` branch..

**Review by ashmaroli — APPROVED** [review]

**Comment by ashmaroli** [comment]
The failures remaining are not from changes to cop-names and should ideally be addressed at the concerned repository.

Thanks @DirtyF 
@jekyllbot: merge +minor

**Pull request merged**
